name: gitleaks

on:
    pull_request:
    push:
        branches: [ master, develop ]

jobs:
    gitleaks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Run gitleaks
              uses: gitleaks/gitleaks-action@v1.6.0
